<?xml version="1.0" encoding="UTF-8"?><testrun name="CountChangeSuite" project="recfun" tests="4" started="4" failures="0" errors="3" ignored="0">
  <testsuite name="recfun.CountChangeSuite" time="0.001">
    <testcase name="countChange: example given in instructions" classname="recfun.CountChangeSuite" time="0.0">
      <error>org.scalatest.exceptions.TestFailedException: 2 did not equal 3&#13;
	at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:318)&#13;
	at recfun.CountChangeSuite.newAssertionFailedException(CountChangeSuite.scala:9)&#13;
	at org.scalatest.Assertions$class.assert(Assertions.scala:401)&#13;
	at recfun.CountChangeSuite.assert(CountChangeSuite.scala:9)&#13;
	at recfun.CountChangeSuite$$anonfun$1.apply$mcV$sp(CountChangeSuite.scala:12)&#13;
	at recfun.CountChangeSuite$$anonfun$1.apply(CountChangeSuite.scala:12)&#13;
	at recfun.CountChangeSuite$$anonfun$1.apply(CountChangeSuite.scala:12)&#13;
	at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1265)&#13;
	at org.scalatest.Suite$class.withFixture(Suite.scala:1974)&#13;
	at recfun.CountChangeSuite.withFixture(CountChangeSuite.scala:9)&#13;
	at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1262)&#13;
	at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1271)&#13;
	at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1271)&#13;
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:198)&#13;
	at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1271)&#13;
	at recfun.CountChangeSuite.runTest(CountChangeSuite.scala:9)&#13;
	at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1304)&#13;
	at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1304)&#13;
	at org.scalatest.SuperEngine$$anonfun$org$scalatest$SuperEngine$$runTestsInBranch$1.apply(Engine.scala:260)&#13;
	at org.scalatest.SuperEngine$$anonfun$org$scalatest$SuperEngine$$runTestsInBranch$1.apply(Engine.scala:249)&#13;
	at scala.collection.immutable.List.foreach(List.scala:318)&#13;
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:249)&#13;
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:326)&#13;
	at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1304)&#13;
	at recfun.CountChangeSuite.runTests(CountChangeSuite.scala:9)&#13;
	at org.scalatest.Suite$class.run(Suite.scala:2303)&#13;
	at recfun.CountChangeSuite.org$scalatest$FunSuite$$super$run(CountChangeSuite.scala:9)&#13;
	at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1310)&#13;
	at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1310)&#13;
	at org.scalatest.SuperEngine.runImpl(Engine.scala:362)&#13;
	at org.scalatest.FunSuite$class.run(FunSuite.scala:1310)&#13;
	at recfun.CountChangeSuite.run(CountChangeSuite.scala:9)&#13;
	at org.scalatest.junit.JUnitRunner.run(JUnitRunner.scala:94)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
&#13;
</error>
    </testcase>
    <testcase name="countChange: sorted CHF" classname="recfun.CountChangeSuite" time="0.0">
      <error>org.scalatest.exceptions.TestFailedException: 5 did not equal 1022&#13;
	at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:318)&#13;
	at recfun.CountChangeSuite.newAssertionFailedException(CountChangeSuite.scala:9)&#13;
	at org.scalatest.Assertions$class.assert(Assertions.scala:401)&#13;
	at recfun.CountChangeSuite.assert(CountChangeSuite.scala:9)&#13;
	at recfun.CountChangeSuite$$anonfun$2.apply$mcV$sp(CountChangeSuite.scala:16)&#13;
	at recfun.CountChangeSuite$$anonfun$2.apply(CountChangeSuite.scala:16)&#13;
	at recfun.CountChangeSuite$$anonfun$2.apply(CountChangeSuite.scala:16)&#13;
	at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1265)&#13;
	at org.scalatest.Suite$class.withFixture(Suite.scala:1974)&#13;
	at recfun.CountChangeSuite.withFixture(CountChangeSuite.scala:9)&#13;
	at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1262)&#13;
	at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1271)&#13;
	at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1271)&#13;
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:198)&#13;
	at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1271)&#13;
	at recfun.CountChangeSuite.runTest(CountChangeSuite.scala:9)&#13;
	at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1304)&#13;
	at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1304)&#13;
	at org.scalatest.SuperEngine$$anonfun$org$scalatest$SuperEngine$$runTestsInBranch$1.apply(Engine.scala:260)&#13;
	at org.scalatest.SuperEngine$$anonfun$org$scalatest$SuperEngine$$runTestsInBranch$1.apply(Engine.scala:249)&#13;
	at scala.collection.immutable.List.foreach(List.scala:318)&#13;
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:249)&#13;
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:326)&#13;
	at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1304)&#13;
	at recfun.CountChangeSuite.runTests(CountChangeSuite.scala:9)&#13;
	at org.scalatest.Suite$class.run(Suite.scala:2303)&#13;
	at recfun.CountChangeSuite.org$scalatest$FunSuite$$super$run(CountChangeSuite.scala:9)&#13;
	at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1310)&#13;
	at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1310)&#13;
	at org.scalatest.SuperEngine.runImpl(Engine.scala:362)&#13;
	at org.scalatest.FunSuite$class.run(FunSuite.scala:1310)&#13;
	at recfun.CountChangeSuite.run(CountChangeSuite.scala:9)&#13;
	at org.scalatest.junit.JUnitRunner.run(JUnitRunner.scala:94)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
&#13;
</error>
    </testcase>
    <testcase name="countChange: no pennies" classname="recfun.CountChangeSuite" time="0.0"/>
    <testcase name="countChange: unsorted CHF" classname="recfun.CountChangeSuite" time="0.001">
      <error>org.scalatest.exceptions.TestFailedException: 5 did not equal 1022&#13;
	at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:318)&#13;
	at recfun.CountChangeSuite.newAssertionFailedException(CountChangeSuite.scala:9)&#13;
	at org.scalatest.Assertions$class.assert(Assertions.scala:401)&#13;
	at recfun.CountChangeSuite.assert(CountChangeSuite.scala:9)&#13;
	at recfun.CountChangeSuite$$anonfun$4.apply$mcV$sp(CountChangeSuite.scala:24)&#13;
	at recfun.CountChangeSuite$$anonfun$4.apply(CountChangeSuite.scala:24)&#13;
	at recfun.CountChangeSuite$$anonfun$4.apply(CountChangeSuite.scala:24)&#13;
	at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1265)&#13;
	at org.scalatest.Suite$class.withFixture(Suite.scala:1974)&#13;
	at recfun.CountChangeSuite.withFixture(CountChangeSuite.scala:9)&#13;
	at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1262)&#13;
	at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1271)&#13;
	at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1271)&#13;
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:198)&#13;
	at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1271)&#13;
	at recfun.CountChangeSuite.runTest(CountChangeSuite.scala:9)&#13;
	at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1304)&#13;
	at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1304)&#13;
	at org.scalatest.SuperEngine$$anonfun$org$scalatest$SuperEngine$$runTestsInBranch$1.apply(Engine.scala:260)&#13;
	at org.scalatest.SuperEngine$$anonfun$org$scalatest$SuperEngine$$runTestsInBranch$1.apply(Engine.scala:249)&#13;
	at scala.collection.immutable.List.foreach(List.scala:318)&#13;
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:249)&#13;
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:326)&#13;
	at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1304)&#13;
	at recfun.CountChangeSuite.runTests(CountChangeSuite.scala:9)&#13;
	at org.scalatest.Suite$class.run(Suite.scala:2303)&#13;
	at recfun.CountChangeSuite.org$scalatest$FunSuite$$super$run(CountChangeSuite.scala:9)&#13;
	at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1310)&#13;
	at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1310)&#13;
	at org.scalatest.SuperEngine.runImpl(Engine.scala:362)&#13;
	at org.scalatest.FunSuite$class.run(FunSuite.scala:1310)&#13;
	at recfun.CountChangeSuite.run(CountChangeSuite.scala:9)&#13;
	at org.scalatest.junit.JUnitRunner.run(JUnitRunner.scala:94)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
